---

- name: ensure kyotocabinet installed
  stat:
    path: /usr/local/stow/kyotocabinet-{{ kc_version }}
  register: install_dir

- name: download archived source
  get_url:
    url: http://fallabs.com/kyotocabinet/pkg/kyotocabinet-{{ kc_version }}.tar.gz
    dest: /tmp
  when: not install_dir.stat.exists

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/kyotocabinet-{{ kc_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not install_dir.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/kyotocabinet-{{ kc_version }}
  with_items:
    - ./configure --prefix=/usr/local/stow/kyotocabinet-{{ kc_version }}
    - make
    - make install
  when: not install_dir.stat.exists

- name: stow
  become: yes
  shell: stow kyotocabinet-{{ kc_version }}
  args:
    chdir: /usr/local/stow
  when: not install_dir.stat.exists
