---

- name: ensure spdlog installed
  stat:
    path: /usr/local/stow/spdlog-{{ spdlog_version }}
  register: install_dir

- name: download archived source
  get_url:
    url: https://github.com/gabime/spdlog/archive/v{{ spdlog_version }}.tar.gz
    dest: /tmp
  when: not install_dir.stat.exists

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/spdlog-{{ spdlog_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not install_dir.stat.exists

- name: create the directory
  become: yes
  file:
    path: /usr/local/stow/spdlog-{{ spdlog_version }}
    state: directory
  when: not install_dir.stat.exists

- name: install
  become: yes
  copy:
    src: /usr/local/src/spdlog-{{ spdlog_version }}/include
    dest: /usr/local/stow/spdlog-{{ spdlog_version }}
  when: not install_dir.stat.exists

- name: stow
  become: yes
  shell: stow spdlog-{{ spdlog_version }}
  args:
    chdir: /usr/local/stow
  when: not install_dir.stat.exists
