---

- name: download archived source
  get_url:
    url: https://github.com/gabime/spdlog/archive/v{{ spdlog_version }}.tar.gz
    dest: /tmp
    sha256sum: bbbe5a855c8b309621352921d650449eb2f741d35d55ec50fb4d8122ddfb8f01
    force: yes

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/spdlog-{{ spdlog_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: install
  become: yes
  copy:
    src: /usr/local/src/spdlog-{{ spdlog_version }}/include/spdlog
    dest: /usr/local/include/
