---

- name: download archived source
  get_url:
    url: https://github.com/gabime/spdlog/archive/v{{ spdlog_version }}.tar.gz
    dest: /tmp

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/spdlog-{{ spdlog_version }}.tar.gz
    dest: /usr/local/src

- name: install
  become: yes
  copy:
    src: /usr/local/src/spdlog-{{ spdlog_version }}/include/spdlog
    dest: /usr/local/include/
