---

- name: add apt repository
  become: yes
  apt_repository:
    repo: ppa:webupd8team/java

- name: create debconf
  become: yes
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: install packages
  become: yes
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes
