---

- name: ensure rbenv installed
  stat:
    path: ~/.rbenv
  register: rbenv_dir

- name: install rbenv
  shell: "{{ item }}"
  with_items:
    - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    - cd ~/.rbenv && src/configure && make -C src
  when: not rbenv_dir.stat.exists
