---

# - name: download jq
#   become: yes
#   get_url:
#     url: https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64
#     dest: /usr/local/bin/jq
#     mode: 0755

- name: download jq
  become: yes
  shell: curl -fsSL https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64 -o /usr/local/bin/jq

- name: add permisson
  become: yes
  file:
    path: /usr/local/bin/jq
    mode: 0755
