---

- name: download archived source
  get_url:
    url: https://github.com/zeromq/czmq/archive/v{{ czmq_version }}.tar.gz
    dest: /tmp

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/czmq-{{ czmq_version }}.tar.gz
    dest: /usr/local/src

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/czmq-{{ czmq_version }}
  with_items:
    - ./autogen.sh
    - ./configure --prefix=/usr/local/stow/czmq-{{ czmq_version }}
    - make
    - make install

- name: stow
  become: yes
  shell: stow czmq-{{ czmq_version }}
  args:
    chdir: /usr/local/stow
