---

- name: ensure libsodium installed
  stat:
    path: /usr/local/stow/libsodium-{{ sodium_version }}
  register: install_dir

# - name: download archived source
#   get_url:
#     url: https://github.com/jedisct1/libsodium/releases/download/{{ sodium_version }}/libsodium-{{ sodium_version }}.tar.gz
#     dest: /tmp
#   when: not install_dir.stat.exists

- name: download archived source
  shell: curl -fsSL https://github.com/jedisct1/libsodium/releases/download/{{ sodium_version }}/{libsodium-{{ sodium_version }}.tar.gz} -o /tmp/#1
  when: not install_dir.stat.exists

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/libsodium-{{ sodium_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not install_dir.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/libsodium-{{ sodium_version }}
  with_items:
    - ./configure --prefix=/usr/local/stow/libsodium-{{ sodium_version }}
    - make
    - make install
  when: not install_dir.stat.exists

- name: stow
  become: yes
  shell: stow libsodium-{{ sodium_version }}
  args:
    chdir: /usr/local/stow
  when: not install_dir.stat.exists
