---

- name: ensure clang installed
  stat:
    path: /usr/local/stow/{{ clang }}
  register: install_dir

- name: download archived file
  get_url:
    url: http://llvm.org/releases/{{ clang_version }}/{{ clang }}.tar.xz
    dest: /tmp
  when: not install_dir.stat.exists

- name: unarchive the file
  become: yes
  unarchive:
    src: /tmp/{{ clang }}.tar.xz
    dest: /usr/local/stow
    remote_src: yes
  when: not install_dir.stat.exists

- name: stow
  become: yes
  shell: stow {{ clang }}
  args:
    chdir: /usr/local/stow
  when: not install_dir.stat.exists
