---

- name: download archived file
  get_url:
    url: http://llvm.org/releases/{{ clang_version }}/{{ clang }}.tar.xz
    dest: /tmp
    sha256sum: 6eba6f834424086a40ca95e7b013765d8bcbfdce193b5ab7da42e2ff5beadf3e

- name: unarchive the file
  become: yes
  unarchive:
    src: /tmp/{{ clang }}.tar.xz
    dest: /usr/local/stow

- name: stow
  become: yes
  shell: stow {{ clang }}
  args:
    chdir: /usr/local/stow
