---

- name: install qmake
  become: yes
  apt:
    name: qt5-qmake
    state: present
    update_cache: yes

- name: create symlink
  become: yes
  file:
    src: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    dest: /usr/local/bin/qmake
    state: link
