---

- name: add dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0644
  with_items:
    - .bashrc
    - .inputrc
    - .vimrc

- name: remove CR code in dotfiles
  replace:
    dest: "{{ item }}"
    regexp: '\r'
    replace: ''
  with_items:
    - ~/.bashrc
    - ~/.inputrc
    - ~/.vimrc
