---

- name: add dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0644
  with_items: "{{ files }}"

- name: remove CR code in dotfiles
  replace:
    path: "~/{{ item }}"
    regexp: '\r'
    replace: ''
  with_items: "{{ files }}"
