---

- name: install pip
  become: yes
  apt:
    name: python-pip
    update_cache: yes

# There modules are needed to run Ansible with python >= 2.6
- name: install python modules
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
