---

- name: download archived source
  get_url:
    url: https://github.com/google/googletest/archive/release-{{ gtest_version }}.tar.gz
    dest: /tmp

- name: unarchive source
  become: yes
  unarchive:
    src: /tmp/googletest-release-{{ gtest_version }}.tar.gz
    dest: /usr/local/src

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/googletest-release-{{ gtest_version }}
  with_items:
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .
    - ninja
    - ninja install
