---

- name: add apt key
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    filename: docker.list
    state: present

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - linux-image-extra-4.4.0-31-generic
    - linux-image-extra-virtual
    - docker-engine
